# Generated by Django 3.1.1 on 2020-09-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200928_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='tag',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tag'),
        ),
    ]
