# Generated by Django 3.1.1 on 2020-09-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200930_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='tag',
            field=models.ForeignKey(default='Deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tag'),
        ),
    ]
