# Generated by Django 3.1.1 on 2020-09-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201001_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
