# Generated by Django 3.1.1 on 2020-09-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201001_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.author'),
            preserve_default=False,
        ),
    ]
